Repository dnd-side-project/dnd-8th-1-backend, pull requests merged in 2023-01, with the labels that each got.

#4 [build] : 프로젝트 환경에 jacoco 설정
  build.gradle
  lombok.config
Labels: ⚙ Setting, 💎 수찬 💎

#6 build : 정적 코드 분석을 위한 SonarCloud 도입
  .github/workflows/sonar-build.yml
  build.gradle
Labels: ⚙ Setting, 💎 수찬 💎

#8 [Test] SonarCloud 커버리지 테스트
  src/main/java/dnd/danverse/domain/member/Member.java
  src/test/java/dnd/danverse/domain/member/MemberTest.java
Labels: ✅ Test, 💎 수찬 💎

#9 [Feat] github action 이용한 배포 환경 구축
  .github/workflows/deploy.yml
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
  src/main/java/dnd/danverse/global/healthcheck/HealthController.java
Labels: ⚙ Setting, 🔮 설희 🔮

#11 [Test] : 무중단 배포를 위한 테스트 api 작성
  src/main/java/dnd/danverse/global/healthcheck/HealthController.java
Labels: ⚙ Setting, ✅ Test, 🔮 설희 🔮
