Repository dnd-side-project/dnd-8th-1-backend, pull requests merged in 2023-02, with the labels that each got.

#16 [Feat] : 구글 소셜 로그인 기능 추가
  .gitignore
  build.gradle
  src/main/java/dnd/danverse/domain/common/BaseTimeEntity.java
  src/main/java/dnd/danverse/domain/jwt/AccessRefreshTokenDto.java
  src/main/java/dnd/danverse/domain/jwt/controller/JwtTokenController.java
  src/main/java/dnd/danverse/domain/jwt/exception/JwtException.java
  src/main/java/dnd/danverse/domain/jwt/exception/JwtExceptionFilter.java
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/dnd/danverse/domain/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/dnd/danverse/domain/jwt/handler/JwtAuthenticationEntryPointHandler.java
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenProvider.java
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenReIssueService.java
  src/main/java/dnd/danverse/domain/jwt/service/SessionUser.java
  src/main/java/dnd/danverse/domain/member/Member.java
  src/main/java/dnd/danverse/domain/member/controller/MemberController.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/member/entity/Member.java
  src/main/java/dnd/danverse/domain/member/entity/Role.java
  src/main/java/dnd/danverse/domain/member/repository/MemberRepository.java
  src/main/java/dnd/danverse/domain/member/service/MemberSignUpService.java
  src/main/java/dnd/danverse/domain/oauth/config/RestTemplateConfig.java
  src/main/java/dnd/danverse/domain/oauth/exception/SocialLoginFailedException.java
  src/main/java/dnd/danverse/domain/oauth/info/OAuth2Provider.java
  src/main/java/dnd/danverse/domain/oauth/info/OAuth2UserInfo.java
  src/main/java/dnd/danverse/domain/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/dnd/danverse/domain/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/dnd/danverse/domain/oauth/info/response/GoogleInfoDto.java
  src/main/java/dnd/danverse/domain/oauth/service/HttpSocialLoginRequest.java
  src/main/java/dnd/danverse/domain/oauth/service/OAuth2Service.java
  src/main/java/dnd/danverse/global/exception/BusinessException.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/exception/ErrorResponse.java
  src/main/java/dnd/danverse/global/exception/GlobalExceptionHandler.java
  src/main/java/dnd/danverse/global/redis/config/RedisConfig.java
  src/main/java/dnd/danverse/global/redis/dto/RefreshTokenDto.java
  src/main/java/dnd/danverse/global/redis/repository/RefreshTokenRedisRepository.java
  src/main/java/dnd/danverse/global/redis/service/RedisService.java
  src/main/java/dnd/danverse/global/response/DataResponse.java
  src/main/java/dnd/danverse/global/response/DefaultResponse.java
  src/main/java/dnd/danverse/global/response/MessageResponse.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/java/dnd/danverse/global/util/CookieUtil.java
  src/main/java/dnd/danverse/global/util/HttpHeaderUtil.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/java/dnd/danverse/domain/member/MemberTest.java
Labels: ⚙ Setting, ✨ Feature, 💎 수찬 💎

#17 [Feat] : mariaDB 연동 및 aws parameter store 설정 추가
  build.gradle
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: ⚙ Setting, 🔮 설희 🔮

#23 [Build] : gitignore 에 설정 파일 추가
  .gitignore
  build.gradle
  src/main/resources/application-prod.properties
Labels: ⚙ Setting, 💎 수찬 💎

#29 [Build] : aws parameter store 적용
  build.gradle
  src/main/java/dnd/danverse/global/redis/config/EmbeddedRedisConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/test/resources/application.properties
Labels: ⚙ Setting, 💎 수찬 💎

#31 [Feat] : 도메인 Entity 구성
  src/main/java/dnd/danverse/ServerApplication.java
  src/main/java/dnd/danverse/domain/common/Genre.java
  src/main/java/dnd/danverse/domain/common/Image.java
  src/main/java/dnd/danverse/domain/common/Location.java
  src/main/java/dnd/danverse/domain/common/TeamType.java
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/event/entitiy/EventType.java
  src/main/java/dnd/danverse/domain/jwt/service/SessionUser.java
  src/main/java/dnd/danverse/domain/matching/entity/EventMatch.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/member/entity/Member.java
  src/main/java/dnd/danverse/domain/member/service/MemberSignUpService.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performgenre/entity/PerformGenre.java
  src/main/java/dnd/danverse/domain/profile/entity/OpenChat.java
  src/main/java/dnd/danverse/domain/profile/entity/Portfolio.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
  src/main/java/dnd/danverse/domain/review/entity/Review.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: ✨ Feature, 💎 수찬 💎

#33 [Build] : querydsl 의존성 주입
  build.gradle
Labels: ⚙ Setting, 💎 수찬 💎

#35 [Refactor] : redis 테스트 코드 병렬적으로 수행시, 포트 충돌 방지
  src/main/java/dnd/danverse/global/redis/config/EmbeddedRedisConfig.java
Labels: ⚙ Setting, ✅ Test, 💎 수찬 💎

#37 [Refactor] : redis 에 저장되는 객체 필드 수정으로, token 관리 대상 최소화
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenReIssueService.java
  src/main/java/dnd/danverse/domain/oauth/service/OAuth2Service.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/exception/GlobalExceptionHandler.java
  src/main/java/dnd/danverse/global/redis/dto/RefreshTokenDto.java
  src/main/java/dnd/danverse/global/redis/repository/RefreshTokenRedisRepository.java
  src/main/java/dnd/danverse/global/redis/service/RedisService.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#39 [Refactor] : SequenceGenerator 에서 GenericGenerator 으로 변경
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/matching/entity/EventMatch.java
  src/main/java/dnd/danverse/domain/member/entity/Member.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performgenre/entity/PerformGenre.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
  src/main/java/dnd/danverse/domain/review/entity/Review.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#41 [Feat] : 지역, 장르 enum class 제거
  src/main/java/dnd/danverse/domain/common/Genre.java
  src/main/java/dnd/danverse/domain/common/Location.java
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performgenre/entity/PerformGenre.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
Labels: ✨ Feature, 🔮 설희 🔮

#46 [Feat] : 임박한 공연 조회 기능 추가
  src/main/java/dnd/danverse/domain/common/Image.java
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/response/ImminentPerformsDto.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepository.java
  src/main/java/dnd/danverse/domain/performance/service/PerformanceService.java
  src/main/java/dnd/danverse/domain/performgenre/PerformGenreRepository.java
  src/main/java/dnd/danverse/domain/performgenre/entity/PerformGenre.java
  src/main/java/dnd/danverse/domain/profile/ProfileRepository.java
  src/main/java/dnd/danverse/domain/profile/entity/OpenChat.java
  src/main/java/dnd/danverse/domain/profile/entity/Portfolio.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profilegenre/ProfileGenreRepository.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
  src/test/java/dnd/danverse/domain/performance/service/PerformanceServiceTest.java
Labels: ✨ Feature, 💎 수찬 💎

#47 [Setting] s3설정 및 로직 추가
  build.gradle
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/s3/controller/S3Controller.java
  src/main/java/dnd/danverse/global/s3/dto/response/S3Dto.java
  src/main/java/dnd/danverse/global/s3/exception/ImageUploadException.java
  src/main/java/dnd/danverse/global/s3/service/S3Uploader.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/resources/application-prod.properties
  src/test/resources/application.properties
Labels: ⚙ Setting, 🔮 설희 🔮

#49 [Feat] : 필터링 할 수 있는 이벤트 전체 조회 기능 추가
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventCondDto.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventInfoResponse.java
  src/main/java/dnd/danverse/domain/event/entitiy/EventType.java
  src/main/java/dnd/danverse/domain/event/exception/TypeNotSupportException.java
  src/main/java/dnd/danverse/domain/event/repository/EventFilterCustom.java
  src/main/java/dnd/danverse/domain/event/repository/EventRepository.java
  src/main/java/dnd/danverse/domain/event/repository/EventRepositoryImpl.java
  src/main/java/dnd/danverse/domain/event/service/EventProfileService.java
Labels: ✨ Feature, 💎 수찬 💎

#55 [Feat] : event 글 등록 기능 추가
  src/main/java/dnd/danverse/domain/common/TeamType.java
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventSavedRequestDto.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventSavedResponseDto.java
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/event/exception/NoProfileException.java
  src/main/java/dnd/danverse/domain/event/exception/TypeNotSupportException.java
  src/main/java/dnd/danverse/domain/event/service/EventService.java
  src/main/java/dnd/danverse/domain/profile/ProfileRepository.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileDto.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/s3/service/S3Uploader.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#56 [Refactor] Token 발급, 재발급 과정 코드 개선
  src/main/java/dnd/danverse/domain/jwt/controller/JwtTokenController.java
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenProvider.java
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenReIssueService.java
  src/main/java/dnd/danverse/domain/member/controller/MemberController.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/member/entity/Member.java
  src/main/java/dnd/danverse/domain/member/entity/Role.java
  src/main/java/dnd/danverse/domain/member/repository/MemberRepository.java
  src/main/java/dnd/danverse/domain/member/service/MemberSignUpService.java
  src/main/java/dnd/danverse/domain/member/service/SignUpResult.java
  src/main/java/dnd/danverse/domain/oauth/dto/OAuth2LoginResponseDTO.java
  src/main/java/dnd/danverse/domain/oauth/info/OAuth2UserInfo.java
  src/main/java/dnd/danverse/domain/oauth/service/OAuth2Service.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileInfoDto.java
  src/main/java/dnd/danverse/domain/profile/entity/OpenChat.java
  src/main/java/dnd/danverse/domain/profile/entity/Portfolio.java
  src/main/java/dnd/danverse/global/redis/repository/RefreshTokenRedisRepository.java
  src/main/java/dnd/danverse/global/redis/service/RedisService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/java/dnd/danverse/global/util/CookieUtil.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#58 [Refactor] : 이벤트 전체 조회 코드 수정
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventInfoResponse.java
  src/main/java/dnd/danverse/domain/event/repository/EventRepositoryImpl.java
  src/main/java/dnd/danverse/domain/event/service/EventFilterService.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#60 [Feat] : 이벤트 신청 기능 추가
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/event/exception/EventNotAvailableException.java
  src/main/java/dnd/danverse/domain/event/exception/EventNotFoundException.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventService.java
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/dto/request/EventIdRequestDto.java
  src/main/java/dnd/danverse/domain/matching/entity/EventMatch.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profile/exception/NoProfileException.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#62 [Refactor] : 이벤트 등록 코드 개선
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventSavedRequestDto.java
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventSaveComplexService.java
  src/main/java/dnd/danverse/domain/event/service/EventService.java
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/test/java/dnd/danverse/domain/performance/service/PerformancePureServiceTest.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#64 [Feat] : 이벤트 신청 취소 기능 추가
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenProvider.java
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/exception/EventMatchNotFoundException.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#66 [Feat] : 이벤트 상세조회 기능 구현 및 개선
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventWithProfileDto.java
  src/main/java/dnd/danverse/domain/event/repository/EventRepository.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventSaveComplexService.java
  src/main/java/dnd/danverse/domain/event/service/EventSearchComplexService.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileSimpleDto.java
Labels: ✨ Feature, ⭐ Refactoring, 🔮 설희 🔮

#68 [Feat] : Swagger 설정 추가
  build.gradle
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/global/swagger/SwaggerConfig.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: ⚙ Setting, 💎 수찬 💎

#70 [Setting] : swagger 문서 추가
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventCondDto.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventSavedRequestDto.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventInfoResponse.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventWithProfileDto.java
  src/main/java/dnd/danverse/domain/jwt/controller/JwtTokenController.java
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/dto/request/EventIdRequestDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileSimpleDto.java
  src/main/java/dnd/danverse/global/response/DataResponse.java
  src/main/java/dnd/danverse/global/response/DefaultResponse.java
  src/main/java/dnd/danverse/global/swagger/SwaggerConfig.java
Labels: ⚙ Setting, 🔮 설희 🔮, 💎 수찬 💎

#72 [Setting] : member 관련 스웨거 매핑 추가
  src/main/java/dnd/danverse/domain/jwt/controller/JwtTokenController.java
  src/main/java/dnd/danverse/domain/member/controller/MemberController.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileInfoDto.java
Labels: ⚙ Setting, 🔮 설희 🔮

#74 [Fix] : Security Config, 권한이 필요한 이벤트 지원 URL 수정
  src/main/java/dnd/danverse/domain/performance/dto/response/PageDto.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: 🛠 Fix, 💎 수찬 💎

#76 [Setting] : CORS 설정 추가
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/resources/application-prod.properties
Labels: ⚙ Setting, ✨ Feature, 💎 수찬 💎

#77 feat : 이벤트 신청자 리스트 조회 기능 추가 (#54)
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/dto/response/ApplicantsResponseDto.java
  src/main/java/dnd/danverse/domain/matching/exception/NotEventWriterException.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/profile/dto/response/MatchProfileDto.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#79 [Refactor] : 이벤트 중복 신청 불가 기능 추가
  src/main/java/dnd/danverse/domain/matching/exception/AlreadyAppliedException.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#81 [Refactor] : entity 에 on delete 제약 조건 추가
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/matching/entity/EventMatch.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/review/entity/Review.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#84 [Feat] : 이벤트 지원자 요청 수락 기능 추가
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/dto/request/ProfileIdRequestDto.java
  src/main/java/dnd/danverse/domain/matching/entity/EventMatch.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventAcceptComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
Labels: ✨ Feature, 💎 수찬 💎

#86 [Feat] : 이벤트 조기 마감 기능 구현
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventUpdateService.java
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchSearchService.java
  src/main/java/dnd/danverse/domain/matching/service/EventWriterValidationService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#88 [Feat] : 이벤트 게시글 수정 기능 추가
  src/main/java/dnd/danverse/domain/common/TeamType.java
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventSavedRequestDto.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventUpdateRequestDto.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventWithProfileDto.java
  src/main/java/dnd/danverse/domain/event/entitiy/Event.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventUpdateService.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileInfoDto.java
  src/main/java/dnd/danverse/global/s3/controller/S3Controller.java
  src/main/java/dnd/danverse/global/s3/dto/response/S3Dto.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/java/dnd/danverse/global/swagger/SwaggerConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#89 [Feat] : 공연 정보글 상세조회 기능 구현
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformDetailResponse.java
  src/main/java/dnd/danverse/domain/performance/exception/PerformanceNotFoundException.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepository.java
  src/main/java/dnd/danverse/domain/performance/service/PerformSearchComplexService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/domain/performgenre/repository/PerformGenreRepository.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ✨ Feature, 🔮 설희 🔮

#91 [Fix] : 가독성을 위한 코드 개선
  src/main/java/dnd/danverse/domain/event/dto/response/EventWithProfileDto.java
  src/main/java/dnd/danverse/domain/event/service/EventSaveComplexService.java
  src/main/java/dnd/danverse/domain/event/service/EventSearchComplexService.java
Labels: 🚿 Cleanup, 🔮 설희 🔮

#93 [Feat] : 이벤트 글 삭제 기능 구현
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/service/EventDeleteService.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#96 [Refactor] : cookie 값 설정 시, secure 속성 추가
  src/main/java/dnd/danverse/global/util/CookieUtil.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#98 [Refactor] : 공연 전체 조회 코드 개선 (데이터 뻥튀기 현상 해결)
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformCondDto.java
  src/main/java/dnd/danverse/domain/performance/dto/response/ImminentPerformsDto.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformInfoResponse.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryImpl.java
  src/main/resources/application.properties
Labels: ⭐ Refactoring, 💎 수찬 💎

#100 [Feat] : 공연 정보 등록 기능 구현
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformSavedRequestDto.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performance/service/PerformSaveComplexService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/domain/performgenre/exception/LimitExceededException.java
  src/main/java/dnd/danverse/domain/performgenre/service/PerformGenrePureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
Labels: ✨ Feature, 🔮 설희 🔮

#102 [Feat] : 팀 이름으로 예정된, 만료된 공연 조회 기능 추가
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformListResponse.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformFilterCustom.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryImpl.java
  src/main/java/dnd/danverse/domain/performance/service/PerformFilterService.java
Labels: ✨ Feature, 💎 수찬 💎

#104 [Feat] : 공연 정보 등록 관련 url을 securityConfig 설정 추가
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#105 [Refactor] : 공연 등록 코드 개선 및 연관 관계 변경
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformSavedRequestDto.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformDetailResponse.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformInfoResponse.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryImpl.java
  src/main/java/dnd/danverse/domain/performance/service/PerformSaveComplexService.java
  src/main/java/dnd/danverse/domain/performgenre/entity/PerformGenre.java
  src/main/java/dnd/danverse/domain/performgenre/service/PerformGenrePureService.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/resources/application.properties
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#107 [Fix] : 삭제된 컨트롤러 기능 복구
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
Labels: 🛠 Fix, 🔮 설희 🔮

#108 [Docs] 공연 관련 API, Swagger 문서 추가
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformSavedRequestDto.java
  src/main/java/dnd/danverse/domain/performance/dto/response/ImminentPerformsDto.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformDetailResponse.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformInfoResponse.java
  src/main/java/dnd/danverse/global/swagger/SwaggerConfig.java
Labels: 📋 Docs, ⭐ Refactoring, 💎 수찬 💎

#109 [Refactor] : swagger 설정 값 수정
  src/main/java/dnd/danverse/global/swagger/SwaggerConfig.java
Labels: 📋 Docs, ⭐ Refactoring, 💎 수찬 💎

#111 [Fix] : 지난 공연으로 판단하는 조건문 수정
  src/main/java/dnd/danverse/domain/performance/service/PerformFilterService.java
Labels: 🛠 Fix, 💎 수찬 💎

#113 [Feat] : 프로필 6개 랜덤 조회 기능 추가
  src/main/java/dnd/danverse/domain/profile/ProfileRepository.java
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileHomeDto.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileSearchService.java
Labels: ✨ Feature, 💎 수찬 💎

#116 [Refactor] : 공연 날짜와 시간까지 반환하도록 수정
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformInfoResponse.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#117 [Feat] : 공연 후기 등록 기능 추가
  src/main/java/dnd/danverse/domain/member/exception/MemberNotFoundException.java
  src/main/java/dnd/danverse/domain/member/repository/MemberRepository.java
  src/main/java/dnd/danverse/domain/member/service/MemberPureService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/domain/review/controller/ReviewController.java
  src/main/java/dnd/danverse/domain/review/dto/request/ReviewContentDto.java
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoDto.java
  src/main/java/dnd/danverse/domain/review/entity/Review.java
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
  src/main/java/dnd/danverse/domain/review/service/ReviewPureService.java
  src/main/java/dnd/danverse/domain/review/service/ReviewSaveComplexService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#118 [Chore] : 응답 값 형식 및 변수명 수정
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoDto.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#120 [Refactor] : 전체 조회 시, page size 15로 고정
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/request/EventCondDto.java
  src/main/java/dnd/danverse/domain/event/repository/EventFilterCustom.java
  src/main/java/dnd/danverse/domain/event/repository/EventRepositoryImpl.java
  src/main/java/dnd/danverse/domain/event/service/EventFilterService.java
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformCondDto.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformFilterCustom.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryImpl.java
  src/main/java/dnd/danverse/domain/performance/service/PerformFilterService.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#121 [Refactor] : 공연 후기 등록 요청 URL 수정
  src/main/java/dnd/danverse/domain/member/service/MemberPureService.java
  src/main/java/dnd/danverse/domain/review/controller/ReviewController.java
  src/main/java/dnd/danverse/domain/review/dto/request/ReviewContentDto.java
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoDto.java
  src/main/java/dnd/danverse/domain/review/service/ReviewSaveComplexService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#124 [Fix] : 요청 DTO의 Page 변수 Integer 타입으로 변경
  src/main/java/dnd/danverse/domain/event/dto/request/EventCondDto.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformCondDto.java
Labels: 🛠 Fix, 💎 수찬 💎

#123 [Feat] : 공연 정보 수정 기능 구현
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformUpdateRequestDto.java
  src/main/java/dnd/danverse/domain/performance/dto/response/PerformDetailResponse.java
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performance/exception/NotSameProfileException.java
  src/main/java/dnd/danverse/domain/performance/service/PerformUpdateComplexService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformWriterValidationService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/domain/performgenre/entity/PerformGenre.java
  src/main/java/dnd/danverse/domain/performgenre/repository/PerformGenreRepository.java
  src/main/java/dnd/danverse/domain/performgenre/service/PerformGenrePureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: 📋 Docs, ✨ Feature, 🔮 설희 🔮

#127 [Feat] : 공연 정보 삭제 기능 구현
  src/main/java/dnd/danverse/domain/performance/controller/PerformanceController.java
  src/main/java/dnd/danverse/domain/performance/service/PerformDeleteService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#128 [Refactor] : validation 객체를 interface 로 추상화
  src/main/java/dnd/danverse/domain/event/service/EventDeleteService.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventUpdateService.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchSearchService.java
  src/main/java/dnd/danverse/domain/matching/service/EventWriterValidationService.java
  src/main/java/dnd/danverse/domain/performance/dto/request/PerformUpdateRequestDto.java
  src/main/java/dnd/danverse/domain/performance/service/PerformUpdateComplexService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformWriterValidationService.java
  src/main/java/dnd/danverse/domain/validation/EventWriterValidationService.java
  src/main/java/dnd/danverse/domain/validation/PerformWriterValidationService.java
  src/main/java/dnd/danverse/domain/validation/WriterValidationService.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#130 [Refactor] : 공연 삭제 시, validation 추상화에 의존하도록 변경
  src/main/java/dnd/danverse/domain/performance/service/PerformDeleteService.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#132 [Feat] : 공연에 대한 후기 조회 기능 구현
  src/main/java/dnd/danverse/domain/profile/repository/ProfileRepository.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/domain/review/controller/ReviewController.java
  src/main/java/dnd/danverse/domain/review/dto/request/ReviewContentDto.java
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoDto.java
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
  src/main/java/dnd/danverse/domain/review/service/ReviewPureService.java
  src/main/java/dnd/danverse/domain/review/service/ReviewSaveComplexService.java
  src/main/java/dnd/danverse/domain/review/service/ReviewsSearchComplexService.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ✨ Feature, ⭐ Refactoring, 💎 수찬 💎

#134 [Feat] : 최신 리뷰 6개 조회 기능 구현
  src/main/java/dnd/danverse/domain/review/controller/ReviewController.java
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoWithPerformDto.java
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
  src/main/java/dnd/danverse/domain/review/service/ReviewPureService.java
  src/main/java/dnd/danverse/domain/review/service/ReviewsSearchComplexService.java
Labels: ✨ Feature, 💎 수찬 💎

#136 [Fix] : 최신 리뷰 조회 시, IndexOutOfBoundsException 해결
  src/main/java/dnd/danverse/domain/review/service/ReviewsSearchComplexService.java
Labels: 🛠 Fix, 💎 수찬 💎

#138 [Feat] : CORS 6006 포트 추가
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#140 [Fix] : security config에 등록된 공연 삭제 URL 수정
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: 🛠 Fix, 💎 수찬 💎

#142 [Refactoring] : 자료구조 변경 및 java docs 추가
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: 📋 Docs, ⭐ Refactoring, 🔮 설희 🔮

#144 [Feat] : 프로필 상세 조회 기능 구현
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileWithGenreDto.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profile/repository/ProfileRepository.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileDetailService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
Labels: 📋 Docs, ✨ Feature, 🔮 설희 🔮

#146 [Feat] : 프론트의 배포 url을 cors 설정 추가
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#148 Feat/#145
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: 🐞Bug, ✨ Feature, 🔮 설희 🔮

#149 [Feat] : 프론트 배포 url 수정한 후에 CORS config 에 추가
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: 🐞Bug, ✨ Feature, 🔮 설희 🔮

#151 fix : ddl 옵션을 none 에서 create 로 변경
  src/main/resources/application-prod.properties
Labels: 🐞Bug, 🔮 설희 🔮

#155 [Build] : prod properties 수정
  src/main/resources/application-prod.properties
Labels: ⚙ Setting, 💎 수찬 💎

#156 [Feat] : 공연 후기 수정 기능 구현
  src/main/java/dnd/danverse/domain/member/entity/Member.java
  src/main/java/dnd/danverse/domain/review/controller/ReviewController.java
  src/main/java/dnd/danverse/domain/review/dto/request/ReviewUpdateDto.java
  src/main/java/dnd/danverse/domain/review/entity/Review.java
  src/main/java/dnd/danverse/domain/review/exception/NotReviewWriterException.java
  src/main/java/dnd/danverse/domain/review/exception/ReviewNotFoundException.java
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
  src/main/java/dnd/danverse/domain/review/service/ReviewPureService.java
  src/main/java/dnd/danverse/domain/review/service/ReviewUpdateComplexService.java
  src/main/java/dnd/danverse/domain/validation/ReviewWriterValidationService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#158 [Feat] : 프로필 등록 기능 구현
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/dto/request/ProfileSaveRequestDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/PortfolioUrl.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileDetailResponseDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileInfoDto.java
  src/main/java/dnd/danverse/domain/profile/entity/Portfolio.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profile/exception/ProfileAlreadyException.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileSaveService.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ✨ Feature, 🔮 설희 🔮

#159 [Setting] : CORS 추가 설정
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ⚙ Setting, 💎 수찬 💎

#162 [Feat] : 응답값 수정 요청 반영
  src/main/java/dnd/danverse/domain/profile/dto/request/ProfileSaveRequestDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/PortfolioUrl.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileDetailResponseDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileWithGenreDto.java
  src/main/java/dnd/danverse/domain/profile/entity/Portfolio.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#164 [Refactor] : 적절한 메시지를 담은 예외 추가 및 코드 수정
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#166 [Refactor] : 토큰 재발급 로직 수정
  src/main/java/dnd/danverse/domain/jwt/controller/JwtTokenController.java
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#167 [Chore] : exclude url 수정
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#170 [Refactor] : Profile ID 대신 Member ID로 반환 하도록 수정 및 프로필 상세 조회 구현
  src/main/java/dnd/danverse/domain/event/dto/response/EventInfoResponse.java
  src/main/java/dnd/danverse/domain/event/entitiy/EventType.java
  src/main/java/dnd/danverse/domain/event/repository/EventRepositoryImpl.java
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/dto/request/ProfileIdRequestDto.java
  src/main/java/dnd/danverse/domain/matching/service/EventAcceptComplexService.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/dto/response/MatchProfileDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/MemberWithProfileDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileDetailResponseDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileHomeDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileInfoDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileSimpleDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileWithGenreDto.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileDetailService.java
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoDto.java
  src/main/java/dnd/danverse/domain/review/dto/response/ReviewInfoWithPerformDto.java
  src/main/java/dnd/danverse/domain/review/service/ReviewsSearchComplexService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
Labels: ✨ Feature, ⭐ Refactoring, 💎 수찬 💎

#171 [Feat] : 자신이 작성한 리뷰를 조회하는 서비스 구현
  src/main/java/dnd/danverse/domain/mypage/controller/MyPageController.java
  src/main/java/dnd/danverse/domain/mypage/dto/response/MyReviewDto.java
  src/main/java/dnd/danverse/domain/mypage/service/MyReviewSearchService.java
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
  src/main/java/dnd/danverse/domain/review/service/ReviewPureService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#173 [Feat] : 자신이 작성한 공연 정보 조회 기능 구현
  src/main/java/dnd/danverse/domain/mypage/controller/MyPageController.java
  src/main/java/dnd/danverse/domain/mypage/dto/response/MyPerformsDto.java
  src/main/java/dnd/danverse/domain/mypage/service/MyPerformSearchService.java
  src/main/java/dnd/danverse/domain/performance/repository/PerformanceRepository.java
  src/main/java/dnd/danverse/domain/performance/service/PerformancePureService.java
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#175 [Fix] : 이벤트 조건이 바인딩 되지 않는 경우, null로 return 하도록 수정
  src/main/java/dnd/danverse/domain/event/entitiy/EventType.java
Labels: 🛠 Fix, 💎 수찬 💎

#178 [Refactor] : 응답 형식 변수명 변경 및 통일
  src/main/java/dnd/danverse/domain/matching/controller/EventMatchController.java
  src/main/java/dnd/danverse/domain/matching/dto/request/MemberIdRequestDto.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/profile/dto/request/ProfileSaveRequestDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileDetailResponseDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileInfoDto.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#180 [Refactor] : CORS 설정 변경
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#182 [Refactor] : 이벤트 상세 조회 시, 사용자의 지원 이력 여부 정보도 함께 반환
  src/main/java/dnd/danverse/domain/event/controller/EventController.java
  src/main/java/dnd/danverse/domain/event/dto/response/EventWithProfileDto.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/event/service/EventSearchComplexService.java
  src/main/java/dnd/danverse/domain/jwt/service/SessionUser.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
Labels: ⭐ Refactoring, 🔮 설희 🔮, 💎 수찬 💎

#183 [Feat] : 사용자가 작성한 이벤트 목록 전체 조회 기능 구현
  src/main/java/dnd/danverse/domain/event/repository/EventRepository.java
  src/main/java/dnd/danverse/domain/event/service/EventPureService.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/mypage/controller/MyPageController.java
  src/main/java/dnd/danverse/domain/mypage/dto/response/MyEventsDto.java
  src/main/java/dnd/danverse/domain/mypage/service/MyEventsSearchService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#184 [Refactor] : CORS에러 해결을 위한 preFlight 요청에 대한 처리 로직 추가
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: 🐞Bug, ⭐ Refactoring, 🔮 설희 🔮

#186 [Refactor] : CORS 재설정
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#189 [Refactor] : cookie 값 설정시 Same Site 옵션 None 으로 수정
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
  src/main/java/dnd/danverse/global/util/CookieUtil.java
Labels: ✨ Feature, 💎 수찬 💎
