Repository dnd-side-project/dnd-8th-1-backend, pull requests merged in 2023-03, with the labels that each got.

#187 [Feat] : 사용자가 지원한 이벤트 목록 조회 기능 구현
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/domain/matching/service/EventMatchPureService.java
  src/main/java/dnd/danverse/domain/mypage/controller/MyPageController.java
  src/main/java/dnd/danverse/domain/mypage/dto/response/MyAppliesDto.java
  src/main/java/dnd/danverse/domain/mypage/dto/response/MyEventsDto.java
  src/main/java/dnd/danverse/domain/mypage/service/MyAppliesSearchService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#191 [Refactor] : CORS 동작 점검 및 코드 정리
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/java/dnd/danverse/global/util/CookieUtil.java
Labels: ⭐ Refactoring, 🚿 Cleanup, 💎 수찬 💎

#193 [Feat] : 사용자 본인의 정보 조회 기능 API 구현
  src/main/java/dnd/danverse/domain/member/controller/MemberController.java
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
  src/main/java/dnd/danverse/domain/member/service/MemberInfoSearchService.java
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ✨ Feature, 🔮 설희 🔮, 💎 수찬 💎

#194 [Refactor] : 주석문 제거 및 SameSite 옵션 None으로 변경
  src/main/java/dnd/danverse/domain/mypage/controller/MyPageController.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/java/dnd/danverse/global/util/CookieUtil.java
Labels: ✨ Feature, 💎 수찬 💎

#196 [Refactor] : 활동 내역 결과 최신순 정렬 기능 추가
  src/main/java/dnd/danverse/domain/event/repository/EventRepository.java
  src/main/java/dnd/danverse/domain/matching/repository/EventMatchRepository.java
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ✨ Feature, 🔮 설희 🔮

#197 [Feat] : dto에 담는 변수값 변경
  src/main/java/dnd/danverse/domain/member/dto/response/MemberResponse.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#199 [Refactor] : profile 이 없는 경우, null check 하는 코드 추가
  src/main/java/dnd/danverse/domain/jwt/service/SessionUser.java
Labels: ⭐ Refactoring, 💎 수찬 💎

#201 [Refactor] : 정규 표현식 적용하여 프런트 배포 url 설정
  src/main/java/dnd/danverse/global/cors/WebMvcConfig.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#203 [Feat] : 프로필 수정 기능 구현
  src/main/java/dnd/danverse/domain/performance/entity/Performance.java
  src/main/java/dnd/danverse/domain/performance/service/PerformUpdateComplexService.java
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/dto/request/ProfileUpdateRequestDto.java
  src/main/java/dnd/danverse/domain/profile/dto/response/ProfileDetailResponseDto.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileUpdateService.java
  src/main/java/dnd/danverse/domain/profilegenre/ProfileGenreRepository.java
  src/main/java/dnd/danverse/domain/profilegenre/entity/ProfileGenre.java
  src/main/java/dnd/danverse/domain/profilegenre/repository/ProfileGenreRepository.java
  src/main/java/dnd/danverse/domain/profilegenre/service/ProfileGenrePureService.java
  src/test/java/dnd/danverse/domain/performance/repository/PerformanceRepositoryTest.java
Labels: ✨ Feature, 🔮 설희 🔮

#205 [Feat] : 후기 삭제 기능 구현
  src/main/java/dnd/danverse/domain/review/controller/ReviewController.java
  src/main/java/dnd/danverse/domain/review/service/ReviewDeleteComplexService.java
  src/main/java/dnd/danverse/domain/review/service/ReviewPureService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#207 [Feat] : 프로필 삭제 기능 구현
  src/main/java/dnd/danverse/domain/profile/controller/ProfileController.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileDeleteComplexService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#209 [Feat] : 회원 탈퇴 기능 구현
  src/main/java/dnd/danverse/domain/member/controller/MemberController.java
  src/main/java/dnd/danverse/domain/member/service/MemberPureService.java
  src/main/java/dnd/danverse/domain/member/service/MemberWithDrawService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
Labels: ✨ Feature, 💎 수찬 💎

#211 [Feat] : 로그아웃 기능 구현
  src/main/java/dnd/danverse/domain/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/dnd/danverse/domain/jwt/service/JwtTokenProvider.java
  src/main/java/dnd/danverse/domain/member/controller/MemberController.java
  src/main/java/dnd/danverse/domain/member/service/MemberLogOutService.java
  src/main/java/dnd/danverse/global/exception/ErrorCode.java
  src/main/java/dnd/danverse/global/redis/dto/LogOutTokenDto.java
  src/main/java/dnd/danverse/global/redis/repository/LogOutTokenRedisRepository.java
  src/main/java/dnd/danverse/global/redis/service/RedisLogOutService.java
  src/main/java/dnd/danverse/global/redis/service/RedisService.java
  src/main/java/dnd/danverse/global/security/config/SecurityConfig.java
  src/main/java/dnd/danverse/global/util/CookieUtil.java
Labels: ✨ Feature, 💎 수찬 💎

#213 [Refactor] : 프로필 장르 수정 시, 값이 올바르게 반영 되도록 수정
  src/main/java/dnd/danverse/domain/profile/service/ProfileUpdateService.java
Labels: 🛠 Fix, 💎 수찬 💎

#215 [Refactor] : 프로필 수정 관련 서비스 리팩토링
  src/main/java/dnd/danverse/domain/profile/dto/response/PortfolioUrl.java
  src/main/java/dnd/danverse/domain/profile/service/ProfilePureService.java
  src/main/java/dnd/danverse/domain/profile/service/ProfileUpdateService.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#217 [Refactor] : 프로필의 포트폴리오 반영 문제 해결
  src/main/java/dnd/danverse/domain/profile/dto/request/ProfileUpdateRequestDto.java
  src/main/java/dnd/danverse/domain/profile/entity/Profile.java
Labels: ⭐ Refactoring, 🔮 설희 🔮

#219 [Refactor] : 최신순으로 후기를 정렬하기 위한 코드를 추가
  src/main/java/dnd/danverse/domain/review/repository/ReviewRepository.java
Labels: ⭐ Refactoring, 💎 수찬 💎
